server:
  port: 0

info:
  component: HealthInt Administration Web

service:
  defaultMinMs: 50
  defaultMaxMs: 60

ribbon:
 serverListRefreshInterval: 10000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 1
